### ISSUE TITLE
createActivity Question

### ISSUE THREAD

**Issue by GuySawyer** [TheThingSystem/node-taas-client#6]
Good day

I want to use the createActivity functionality of the steward to implement some rule logic.

createActivity requires an "event" and a "task" as inputs. My question actually pertains to the createTask specifically. I see that createTask requires an actor as an input. To my knowledge, actor applies to all devices that fit that prototype.

So all in all, I want to implement some rule logic that monitors events and fires tasks based on devices, not actors. Is this possible?

**Comment by mrose17** [comment]
an actor is either a group of devices (the important word here is "group") or a device or "place/1"

the confusion is that there is an API call that lets you perform a task on all devices having a common prefix, (e.g., all lights). that's a shortcut instead of having to create a group with all those devices and then doing a perform on that group.

does that make sense?

**Comment by GuySawyer** [comment]
Ok, Yes that makes sense. Then to clear it up, I will be using the "createEvent" and "createTask" functions. After that I will use those as inputs to the createActivity.

Correct me if I am wrong, you are saying that the "actor" I put into "createEvent" and "createTask" can be a specific device?

So for example, when I call "createTask", I can use a deviceID as the "actor" parameter?

**Comment by mrose17** [comment]
thanks for the reply. the argument should be like either "place/1" or "device/N" or "group/N", where N is the deviceID or groupID. if you're using a group, then it must be a device group (not an event or task group) for the actor.

**Comment by GuySawyer** [comment]
Perfect, that's exactly what I wanted to hear :)

Now to get it working.

Thank you.

**Comment by mrose17** [comment]
great!  good luck!

**Comment by GuySawyer** [comment]
Work on the activities is going well. I should be able to test out some simple rules this afternoon. I just have another question after noticing something in the node-taas-client.

I see there is a function "performActivity". Aren't the activities supposed to function on their own within the Steward? ie: wait for the specified event, and perform the specified task. So with this in mind, why is there provision for a performActivity?

Thanks

**Comment by mrose17** [comment]
great!

it's just a convenience function. all it does is a perform task on the task associated with the activity. it's not needed in any since, because to use it you need to know the activityID, and if you know that, you also know the task information associated with the activity. it's just there for "completeness".
